config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  root 'users#index'
  resources :users do
    resources :posts do
      resources :likes
      resources :comments
    end
  end

  namespace :api do
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :update_posts_counter
  after_destroy :decrease_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, allow_blank: true }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, allow_blank: true }

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def decrease_posts_counter
    author.decrement!(:posts_counter)
  end

  def recent_5_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApiController
  respond_to :json

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    respond_with @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts, :comments).find(params[:user_id])
    @user_posts = @user.posts.includes(:author, :comments, :likes).all
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to user_posts_path
    else
      flash[:error] = 'There is an error'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def no_posts?(user_posts)
    user_posts.empty?
  end
end

app/views/posts/index.html.erb
<section class='bg-gray-100 p-6 mt-20 mx-8'>
  <div class="flex items-center gap-6">
    <img class="w-16 h-16 object-cover rounded-full mr-4" src="<%= @user.photo %>">
    <div class="ml-2">
      <p class="text-lg font-medium">User name: <%= @user.name %></p>
      <p class="text-gray-500 text-sm">Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>
  <% if no_posts?(@user_posts) %>
   <p class="text-lg font-medium mt-8">No posts to show.</p>
  <% end %>
  <% @user_posts.includes(:comments).order(created_at: :desc).each do |post| %>
    <div class="border rounded-lg hover:bg-gray-300 cursor-pointer my-2" onclick="window.location.href='/users/<%= @user.id %>/posts/<%= post.id %>'">
      <div class='p-4'>
        <h2 class='text-xl font-medium'><%=post.title%></h2>
        <p class='text-gray-500 mt-2'><%=post.text%></p>
        <p class="text-gray-500 mt-2">Comments: <%=post.comments_counter || 0 %>, Likes: <%=post.likes_counter || 0 %></p>
      </div> 
      <div class="bg-gray-200 px-4 py-2">
        <h3 class='text-lg font-medium'>Comments</h3>
        <% unless any_comments?(post) %>
          <p>No comments yet.</p>
        <% else %>
          <% post.recent_5_comments.each do |comment| %>
            <div class='text-gray-500'>
              <i><%= comment.author.name %>: <%= comment.text %></i>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <%end%>
</section>

app/views/posts/new.html.erb
<section class="bg-gray-100 p-6 mt-20 mx-8">
  <h2 class="text-2xl font-bold mb-4">Create a Post</h2>
  <%= form_with model: @post, url: user_posts_path(current_user) do |form| %>
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form.label :title, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      <%= form.label :text, class: "block text-gray-700 font-bold mb-2 mt-4" %>
      <%= form.text_area :text, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      <%= form.submit "Create a Post", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class='bg-gray-100 p-6 mt-20 mx-8'>
  <button class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-2 rounded' onclick="window.location.href='/users/<%= @post.author_id %>/'">Back to User
  </button>
  <div class='flex flex-col gap-8 mb-2 justify-around'>
    <div class='flex flex-col items-start justify-center'>
      <div class='text-xl mt-2'>
        <h2 class="font-bold">
          <%= @post.title %> <i>by</i> <%= @post.author.name %>
        </h2>
        <p class="text-gray-500 text-sm mt-1">
          Comments: <%= @post.comments_counter || 0 %>
          Likes: <%= @post.likes_counter || 0 %>
        </p>
      </div>
      <p class='text-lg my-2 p-8 border-x-2 sm:w-2/3'><%= @post.text%> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquet, ligula ac accumsan posuere, est dolor posuere orci, nec iaculis neque lectus ut orci. Quisque sodales dui et rutrum egestas. Vivamus commodo, urna ut vehicula malesuada, sem elit mollis erat, ut placerat felis elit vitae purus. Praesent fringilla nulla vitae.</p>
      </p>
      <% if can? :delete, @post %>          
        <%= link_to  user_post_path, data: { turbo_method: :delete }, class: 'btn delete-btn' do %>
          Delete Post
        <% end %>
      <% end %>
    </div>
    <div class='flex flex-col'>
      <h3 class="text-lg font-bold">Comments</h3>
      <% unless any_comments?(@post) %>
        <p>No comments yet.</p>
      <% else %>
        <% @post.comments.each do |comment| %>
          <div>
            <i><%= comment.author.name %>: <%= comment.text %></i>
            <% if can? :delete, comment %>
              <%= link_to user_post_comment_path(post_id: params[:id], id: comment.id), data: { turbo_method: :delete } do %>
                Delete
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
    <div>
      <%= form_with model: @comment, class: "w-96 flex flex-col gap-2", url: user_post_comments_path(@post.author, @post, @comment) do |form| %>
        <%= form.text_area :text, class: "p-2 rounded-md border-gray-400 focus:outline-none focus:border-blue-400 resize-none" %>
        <%= form.hidden_field :author_id, value: @post.author.id %>
        <%= form.hidden_field :post_id, value: @post.id %>
        <%= button_tag type: 'submit', class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' do %>
        Post a Comment
        <% end %>
      <% end %>
    </div>
    <div class='like-form'>
      <%= form_with model: @like, url: user_post_likes_path(@post.author, @post, @like) do |form| %>
        <%= form.hidden_field :post_id, value: @post.id %>
        <%= button_tag type: 'submit', class:'bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mt-2' do %>
          Like
        <% end %>
      <% end %>
    </div>
  </div>
</section>